version: '3.3'


services:
  web:
    build: .
    container_name: journal
    depends_on:
      - db
    command: gunicorn journal.wsgi:application --bind 0.0.0.0:8000 -w 4 --reload
    expose:
      - 8000
    volumes:
      - ./static/:/journal/static
    env_file:
      - ./dev.env
  db:
    image: postgres
    environment:
      - POSTGRES_DB=students
      - POSTGRES_USER=bogdan
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgres/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./static/:/journal/static
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - web
  
volumes:
  postgres_data:


