FROM nginx:latest

ARG MAIL=uxui.des@gmail.com
ARG DOMAINS=innotech.space


RUN apt-get update \
    && apt-get install -y cron certbot python-certbot-nginx bash wget \
    && certbot certonly --standalone --agree-tos -m "${MAIL}" -n -d ${DOMAINS} \
    && rm -rf /var/lib/apt/lists/* \
    && echo "PATH=$PATH" > /etc/cron.d/certbot-renew  \
    && echo "@monthly certbot renew --nginx >> /var/log/cron.log 2>&1" >>/etc/cron.d/certbot-renew \
    && crontab /etc/cron.d/certbot-renew


VOLUME /etc/letsencrypt

CMD [ "sh", "-c", "cron && nginx -g 'daemon off;'" ]