version: '3.5'


services:
  web:
    build: .
    tty: true
    container_name: journal
    ports:
      - "8000:8000"
    env_file:
      - ./dev.env
    command: bash -c "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8000 journal.wsgi --workers 3"
    volumes:
      - .:/journal
    networks:
      main_net:
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_web
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=bogdan
      - POSTGRES_DB=students
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      main_net:


  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile-nginx
      network: host
    container_name: proxy_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static/:/journal/static
      - ./media/:/journal/media
      - ./nginx/:/etc/nginx/conf.d
      - letsencrypt:/etc/letsencrypt     
    depends_on:
      - web
    networks:
      main_net:


volumes:
  postgres_data:
  letsencrypt:

networks:
  main_net:






