version: '3.9'


services:
  web:
    build: 
      context: .
    command: gunicorn journal.wsgi:application --bind 0.0.0.0:8000 --workers=4
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=students
      - POSTGRES_USER=bogdan
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgres/data/
    
  
volumes:
  postgres_data:
